import numpy as np
from openresim.grids import CartGrid

dx = 100
dy = 100
dz = 50
    
grid = CartGrid(nx=2, ny=1, nz=1, dx=dx, dy=dy, dz=dz, phi=0.27, k=270)
grid.show(boundary=True)
grid.show(boundary=False)
grid = CartGrid(nx=1, ny=2, nz=1, dx=dx, dy=dy, dz=dz, phi=0.27, k=270)
grid.show(boundary=True)
grid.show(boundary=False)
grid = CartGrid(nx=1, ny=1, nz=2, dx=dx, dy=dy, dz=dz, phi=0.27, k=270)
grid.show(boundary=True)
grid.show(boundary=False)
grid = CartGrid(nx=2, ny=2, nz=1, dx=dx, dy=dy, dz=dz, phi=0.27, k=270)
grid.show(boundary=True)
grid.show(boundary=False)
grid = CartGrid(nx=1, ny=2, nz=2, dx=dx, dy=dy, dz=dz, phi=0.27, k=270)
grid.show(boundary=True)
grid.show(boundary=False)
grid = CartGrid(nx=2, ny=1, nz=2, dx=dx, dy=dy, dz=dz, phi=0.27, k=270)
grid.show(boundary=True)
grid.show(boundary=False)
grid = CartGrid(nx=2, ny=2, nz=2, dx=dx, dy=dy, dz=dz, phi=0.27, k=270)
grid.show(boundary=True)
grid.show(boundary=False)

grid = CartGrid(nx=3, ny=1, nz=1, dx=dx, dy=dy, dz=dz, phi=0.27, k=270)
grid.show(boundary=True)
grid.show(boundary=False)
grid = CartGrid(nx=1, ny=3, nz=1, dx=dx, dy=dy, dz=dz, phi=0.27, k=270)
grid.show(boundary=True)
grid.show(boundary=False)
grid = CartGrid(nx=1, ny=1, nz=3, dx=dx, dy=dy, dz=dz, phi=0.27, k=270)
grid.show(boundary=True)
grid.show(boundary=False)
grid = CartGrid(nx=3, ny=3, nz=1, dx=dx, dy=dy, dz=dz, phi=0.27, k=270)
grid.show(boundary=True)
grid.show(boundary=False)
grid = CartGrid(nx=1, ny=3, nz=3, dx=dx, dy=dy, dz=dz, phi=0.27, k=270)
grid.show(boundary=True)
grid.show(boundary=False)
grid = CartGrid(nx=3, ny=1, nz=3, dx=dx, dy=dy, dz=dz, phi=0.27, k=270)
grid.show(boundary=True)
grid.show(boundary=False)
grid = CartGrid(nx=3, ny=3, nz=3, dx=dx, dy=dy, dz=dz, phi=0.27, k=270)
grid.show(boundary=True)
grid.show(boundary=False)